### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by synacktraa** [KillianLucas/aifs#1]
**Are PRs welcome?**

**Comment by KillianLucas** [comment]
Hi @synacktraa — absolutely! This is just the early days of this project, built to be used by Open Interpreter mainly. I will try to keep it minimal but fixes are especially appreciated.

**Comment by synacktraa** [comment]
**Stuff I've solved and added(still working on few things):**
- Uses Qdrant vectorstore which allows filtering(Additionally it's easier to install than Chroma)
- Checks relative path so doesn't index the files again.
- Indexes new files of indexed directory
- Deletes index of files if it has been deleted from the directory
- Terminal Integration.
