### ISSUE TITLE
demo on colab

### ISSUE THREAD

**Issue by vasnt** [KillianLucas/aifs#3]
Can someone create its google colab sheet for demo?

**Comment by KillianLucas** [comment]
yes, done! thanks for the suggestion @vasnt!

https://colab.research.google.com/drive/1QdXPchTDnzW6I_3HTZFpSeak_XoH81v5?usp=sharing

**Comment by vasnt** [comment]
it works as intended, i added my custom query. & it gave expected (highlighted in green) reply. Thanks for your continual efforts.

<img width="928" alt="image" src="https://github.com/KillianLucas/aifs/assets/117589240/3508b69e-3597-464e-b8f3-cc42db39be53">
